- name: Mount VMFS datastores to ESXi.
  community.vmware.vmware_host_datastore:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datastore_name: "{{ item.name }}"
    datastore_type: "{{ item.type }}"
    vmfs_device_name: "{{ item.device_name }}"
    vmfs_version: "{{ item.version | default(6) }}"
    esxi_hostname: "{{ vcenter_esxi_hosts[0] }}"
    validate_certs: false
    state: present
  loop: "{{ vcenter_host_datastore }}"
  delegate_to: localhost

- name: Configure Storage I/O Control of an mounted datastore.
  community.vmware.vmware_datastore_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter_name: "{{ vcenter_datacenter }}"
    name: "{{ item.name }}"
    storage_io_control: "{{ item.storage_io_control | default('enable_io_statistics') }}"
    congestion_threshold_manual: "{{ item.congestion_threshold_manual | default(30) }}"
    statistic_collection: "{{ item.statistic_collection | default(true) | bool }}"
    validate_certs: false
  loop: "{{ vcenter_host_datastore }}"
  delegate_to: localhost
