---
- name: Manage VMware vSphere Datacenters.
  include: "datacenter.yml"
  tags: datacenter

- name: Manage VMware vSphere Clusters.
  include: "cluster.yml"
  tags: clusters

- name: Manage VMware vSphere ESXi host.
  include: "host.yml"
  tags: host

- name: Manage VMware ESXi host portgroup.
  include: "portgroup.yml"
  when: vcenter_host_portgroup.enable | bool
  tags: portgroup

- name: Manage a datastore on ESXi host.
  include: "host_datastore.yml"
  when: vcenter_host_datastore is defined
  tags: host_datastore

- name: Manage VMware vCenter license keys.
  include: "license.yml"
  tags: license

- name: Manage VMware tags.
  include: "tag.yml"
  when: vcenter_tag is defined
  tags: tag
